Hot model upgrade
deflect-ca/baskerville pull request #65
Opened 2020-12-24 17:07 UTC by mazhurin

Predicting pipeline periodically checks the database for a newly trained model. If the new model exists, the task is reloading the model on the fly.

2021-01-12 09:44 UTC, mkaranasou requested changes
Nice thinking about the time configuration :) 👍

2021-01-12 09:44 UTC, mkaranasou commented on src/baskerville/models/pipeline_tasks/service_provider.py
> +
As we talked about it, it would be best not to load the new model at the start of the batch but at the end of the batch so that we don't delay the processing. :)

2021-01-12 09:44 UTC, mkaranasou commented on src/baskerville/models/config.py
> +    new_model_check_in_seconds = 300
Good thinking about the time restraint. 👍 How do we disable this though? `None`?

2021-01-12 09:44 UTC, mkaranasou commented on src/baskerville/models/pipeline_tasks/service_provider.py
> +    def load_model_from_db(self):
🤔 It is not really only (re)loading the model from db though. I think the part after `self.model_index = new_model_index` should be under the instantiation method?

2021-01-14 17:36 UTC, mazhurin reviewed
I added a new task RefreshModel into the prediction pipeline.

2021-02-01 17:24 UTC, merged